version: '2'
services:
  consent-admingui:
    image: kvalitetsit/consent-admingui:latest
    environment:
      - CONSENTSERVICE_URL=http://consentservice
      - CONTEXT=cag
      - SERVER_PORT=8080
      - LOG_LEVEL=DEBUG
    ports:
      - "8100:8080"